### ISSUE TITLE
Make Mongeez compatible with Mongo 3.0

### ISSUE THREAD

**Issue by d0x** [secondmarket/mongeez#50]
Mongeeze is using the depcriated `ensureIndex` method.  When pinning the new driver, we get an `NoSuchMethodException`.

```
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.0.1</version>
        </dependency>
```

```
Caused by: java.lang.NoSuchMethodError: com.mongodb.DBCollection.ensureIndex(Lcom/mongodb/DBObject;)V
	at org.mongeez.dao.MongeezDao.ensureChangeSetExecutionIndex(MongeezDao.java:107) ~[mongeez-0.9.4.jar:na]
	at org.mongeez.dao.MongeezDao.configure(MongeezDao.java:50) ~[mongeez-0.9.4.jar:na]
	at org.mongeez.dao.MongeezDao.<init>(MongeezDao.java:43) ~[mongeez-0.9.4.jar:na]
	at org.mongeez.ChangeSetExecutor.<init>(ChangeSetExecutor.java:36) ~[mongeez-0.9.4.jar:na]
	at org.mongeez.Mongeez.process(Mongeez.java:40) ~[mongeez-0.9.4.jar:na]
```

I don't know whether this is the only requiered change.

But that one should be fixed calling `DBCollection.createIndex` instead of `DBCollection.ensureIndex`.

![image](https://cloud.githubusercontent.com/assets/2202723/7611757/e3275908-f986-11e4-9625-866513b8ca90.png)

Best Regards.

**Comment by d0x** [comment]
I just saw that @amoschov  fixes this in https://github.com/secondmarket/mongeez/pull/49 .

**Comment by dennisa** [comment]
Where can I download a built version of this?

**Comment by volyihin** [comment]
+1

**Comment by prateekpatil** [comment]
+1 Please let us know when we can have latest build version

**Comment by murugesan70** [comment]
+1. We are already stuck now and we don't see a 0.9.5 build version to download. Could you let us know when it would be available?

**Comment by thiagogcm** [comment]
+1

**Comment by Selectorrr** [comment]
+1

**Comment by patricksuter** [comment]
+1

**Comment by impakt42** [comment]
+1

**Comment by meshuga** [comment]
https://github.com/secondmarket/mongeez/issues/48#issuecomment-145546957
I think the project is kind of dead + plus when taking https://github.com/secondmarket/mongeez/issues/51 into account I think it might be better to start something new.
